### **Day 2: Pandas로 데이터 조작하기 문제집**

Pandas를 활용한 데이터 조작 문제집입니다. 각 문제에 대한 상세한 설명과 함께, 문제 해결에 도움이 되는 **힌트**를 참고하여 코드를 작성해 보세요.

---

#### **1. 붓꽃 데이터셋 (Iris Dataset)**

**문제 1. 데이터 불러오기 및 탐색**
* **문제 설명:** scikit-learn에서 붓꽃 데이터를 불러와 DataFrame으로 만드세요. `df.shape`와 `df.columns`를 사용하여 데이터의 크기와 열 이름을 확인하세요.
* **HINT:** `load_iris()` 함수로 데이터를 불러온 후, `pd.DataFrame()`으로 DataFrame을 만들고 `columns`에 `iris.feature_names`를 지정해 보세요.

In [3]:
from sklearn.datasets import load_iris
import pandas as pd

iris = load_iris()
df = pd.DataFrame(iris.data, columns=iris.feature_names)

df.columns

# 코드를 작성하세요
# 예상 출력: 데이터의 크기 (150, 4)와 열 이름

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)'],
      dtype='object')

In [4]:
df.shape

(150, 4)

**문제 2. 특정 조건으로 데이터 선택**
* **문제 설명:** 'species' 열의 값이 'setosa'인 행만 필터링하여 새로운 DataFrame을 만드세요.
* **HINT:** `df['species'] == 'setosa'`라는 불리언 조건으로 DataFrame을 필터링해 보세요.

In [5]:
from sklearn.datasets import load_iris
import pandas as pd
iris = load_iris()
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df['species'] = iris.target_names[iris.target]

setosa_df = df[df['species'] == 'setosa']

setosa_df
# 코드를 작성하세요
# 예상 출력: 'setosa' 종으로만 구성된 DataFrame

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa
5,5.4,3.9,1.7,0.4,setosa
6,4.6,3.4,1.4,0.3,setosa
7,5.0,3.4,1.5,0.2,setosa
8,4.4,2.9,1.4,0.2,setosa
9,4.9,3.1,1.5,0.1,setosa
10,5.4,3.7,1.5,0.2,setosa
11,4.8,3.4,1.6,0.2,setosa
12,4.8,3.0,1.4,0.1,setosa
13,4.3,3.0,1.1,0.1,setosa
14,5.8,4.0,1.2,0.2,setosa
15,5.7,4.4,1.5,0.4,setosa
16,5.4,3.9,1.3,0.4,setosa
17,5.1,3.5,1.4,0.3,setosa
18,5.7,3.8,1.7,0.3,setosa
19,5.1,3.8,1.5,0.3,setosa
20,5.4,3.4,1.7,0.2,setosa
21,5.1,3.7,1.5,0.4,setosa
22,4.6,3.6,1.0,0.2,setosa
23,5.1,3.3,1.7,0.5,setosa
24,4.8,3.4,1.9,0.2,setosa
25,5.0,3.0,1.6,0.2,setosa
26,5.0,3.4,1.6,0.4,setosa
27,5.2,3.5,1.5,0.2,setosa
28,5.2,3.4,1.4,0.2,setosa
29,4.7,3.2,1.6,0.2,setosa
30,4.8,3.1,1.6,0.2,setosa
31,5.4,3.4,1.5,0.4,setosa
32,5.2,4.1,1.5,0.1,setosa
33,5.5,4.2,1.4,0.2,setosa
34,4.9,3.1,1.5,0.2,setosa
35,5.0,3.2,1.2,0.2,setosa
36,5.5,3.5,1.3,0.2,setosa
37,4.9,3.6,1.4,0.1,setosa
38,4.4,3.0,1.3,0.2,setosa
39,5.1,3.4,1.5,0.2,setosa
40,5.0,3.5,1.3,0.3,setosa
41,4.5,2.3,1.3,0.3,setosa
42,4.4,3.2,1.3,0.2,setosa
43,5.0,3.5,1.6,0.6,setosa
44,5.1,3.8,1.9,0.4,setosa
45,4.8,3.0,1.4,0.3,setosa
46,5.1,3.8,1.6,0.2,setosa
47,4.6,3.2,1.4,0.2,setosa
48,5.3,3.7,1.5,0.2,setosa
49,5.0,3.3,1.4,0.2,setosa

**문제 3. 그룹별 평균 계산**
* **문제 설명:** 'species' 열을 기준으로 데이터를 그룹화하고, 각 그룹의 'sepal length (cm)' 평균을 계산하세요.
* **HINT:** `df.groupby()`를 사용하여 'species'로 그룹화한 뒤, `['sepal length (cm)'].mean()`으로 평균을 구하세요.

In [6]:
from sklearn.datasets import load_iris
import pandas as pd
iris = load_iris()
# sklearn에서 제공하는 '아이리스(붓꽃)' 데이터셋을 불러와요.
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df['species'] = iris.target_names[iris.target]
# iris 데이터(꽃받침 길이, 너비, 꽃잎 길이, 너비)를 판다스 데이터프레임으로 만드는데,
# 열 이름(컬럼명)은 iris.feature_names에서 가져와요.


length_df = df.groupby('species')
length_df['sepal length (cm)'].mean()


# 코드를 작성하세요
# 예상 출력: 종별 sepal length의 평균

species
setosa        5.006
versicolor    5.936
virginica     6.588
Name: sepal length (cm), dtype: float64

**문제 4. 행과 열을 인덱스로 선택**
* **문제 설명:** `.loc`를 사용하여 50번째 행의 'petal length (cm)' 값을 선택하세요.
* **HINT:** `.loc`는 라벨을 기반으로 데이터를 선택합니다. `df.loc[행라벨, 열라벨]` 형태로 사용해 보세요.

In [7]:
from sklearn.datasets import load_iris
import pandas as pd
iris = load_iris()
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df['species'] = iris.target_names[iris.target]


df.loc[51,'petal length (cm)']
# 코드를 작성하세요
# 예상 출력: 붓꽃 데이터의 특정 값

4.5

**문제 5. 데이터 정렬**
* **문제 설명:** 'petal length (cm)' 열을 기준으로 데이터를 내림차순으로 정렬하세요.
* **HINT:** `.sort_values()` 메서드를 사용하고, `by='컬럼명'`과 `ascending=False` 옵션을 지정해 보세요.

In [8]:
from sklearn.datasets import load_iris
import pandas as pd
iris = load_iris()
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df['species'] = iris.target_names[iris.target]

df.sort_values(by ='petal length (cm)', ascending =False)   ##['petal length (cm)']  ## ascending은 False면 내림차순 True는 오름차순 
# 코드를 작성하세요
# df['petal length (cm)'].sort_values(ascending =False)

# 예상 출력: 'petal length (cm)' 값이 큰 순서대로 정렬된 DataFrame

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species
118,7.7,2.6,6.9,2.3,virginica
122,7.7,2.8,6.7,2.0,virginica
117,7.7,3.8,6.7,2.2,virginica
105,7.6,3.0,6.6,2.1,virginica
131,7.9,3.8,6.4,2.0,virginica
...,...,...,...,...,...
16,5.4,3.9,1.3,0.4,setosa
35,5.0,3.2,1.2,0.2,setosa
14,5.8,4.0,1.2,0.2,setosa
13,4.3,3.0,1.1,0.1,setosa
22,4.6,3.6,1.0,0.2,setosa

---

#### **2. 당뇨병 데이터셋 (Diabetes Dataset)**

**문제 1. 데이터 불러오기 및 통계 요약**
* **문제 설명:** scikit-learn에서 당뇨병 데이터를 불러와 DataFrame으로 만드세요. `.describe()` 메서드를 사용하여 각 열의 통계량을 요약하세요.
* **HINT:** `load_diabetes()` 함수로 데이터를 불러온 후 `pd.DataFrame()`으로 만드세요. `diabetes.feature_names`를 `columns`로 지정해야 합니다.

In [9]:
from sklearn.datasets import load_diabetes
import pandas as pd
diabetes = load_diabetes()
df = pd.DataFrame(diabetes.data, columns= diabetes.feature_names)
df.describe()
# 코드를 작성하세요
# 예상 출력: 각 열의 count, mean, std 등 요약 통계

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
count,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02
mean,-2.511817e-19,1.230790e-17,-2.245564e-16,-4.797570e-17,-1.381499e-17,3.918434e-17,-5.777179e-18,-9.042540e-18,9.293722e-17,1.130318e-17
std,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02
min,-1.072256e-01,-4.464164e-02,-9.027530e-02,-1.123988e-01,-1.267807e-01,-1.156131e-01,-1.023071e-01,-7.639450e-02,-1.260971e-01,-1.377672e-01
25%,-3.729927e-02,-4.464164e-02,-3.422907e-02,-3.665608e-02,-3.424784e-02,-3.035840e-02,-3.511716e-02,-3.949338e-02,-3.324559e-02,-3.317903e-02
50%,5.383060e-03,-4.464164e-02,-7.283766e-03,-5.670422e-03,-4.320866e-03,-3.819065e-03,-6.584468e-03,-2.592262e-03,-1.947171e-03,-1.077698e-03
75%,3.807591e-02,5.068012e-02,3.124802e-02,3.564379e-02,2.835801e-02,2.984439e-02,2.931150e-02,3.430886e-02,3.243232e-02,2.791705e-02
max,1.107267e-01,5.068012e-02,1.705552e-01,1.320436e-01,1.539137e-01,1.987880e-01,1.811791e-01,1.852344e-01,1.335973e-01,1.356118e-01

**문제 2. 여러 조건으로 데이터 필터링**
* **문제 설명:** 'age'가 0.05보다 크고 'bmi'가 0.04보다 작은 행만 필터링하여 DataFrame을 만드세요.
* **HINT:** 두 개의 조건을 `&` 연산자로 연결하고, 각 조건을 괄호로 묶어주세요. (예: `df[(조건1) & (조건2)]`)

In [13]:
from sklearn.datasets import load_diabetes
import pandas as pd
diabetes = load_diabetes()
df = pd.DataFrame(diabetes.data, columns=diabetes.feature_names)
df['target'] = diabetes.target

filter_df= df[(df['age']>0.05) & (df['bmi']<0.04)]

filter_df
# 코드를 작성하세요
# 예상 출력: 두 조건을 모두 만족하는 행들로만 구성된 DataFrame

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6,target
7,0.063504,0.050680,-0.001895,0.066629,0.090620,0.108914,0.022869,0.017703,-0.035816,0.003064,63.0
17,0.070769,0.050680,0.012117,0.056301,0.034206,0.049416,-0.039719,0.034309,0.027364,-0.001078,144.0
28,0.052606,-0.044642,-0.021295,-0.074527,-0.040096,-0.037639,-0.006584,-0.039493,-0.000612,-0.054925,131.0
29,0.067136,0.050680,-0.006206,0.063187,-0.042848,-0.095885,0.052322,-0.076395,0.059424,0.052770,283.0
48,0.067136,0.050680,-0.041774,0.011544,0.002559,0.005889,0.041277,-0.039493,-0.059471,-0.021788,75.0
51,0.059871,0.050680,0.016428,0.028758,-0.041472,-0.029184,-0.028674,-0.002592,-0.002398,-0.021788,225.0
59,0.063504,0.050680,-0.025607,0.011544,0.064477,0.048477,0.030232,-0.002592,0.038394,0.019633,170.0
64,0.067136,0.050680,-0.025607,-0.040099,-0.063487,-0.059873,-0.002903,-0.039493,-0.019198,0.011349,71.0
72,0.063504,0.050680,-0.004050,-0.012556,0.103003,0.048790,0.056003,-0.002592,0.084492,-0.017646,202.0
80,0.070769,-0.044642,0.012117,0.042529,0.071357,0.053487,0.052322,-0.002592,0.025395,-0.005220,143.0
96,0.056239,0.050680,0.009961,0.049415,-0.004321,-0.012274,-0.043401,0.034309,0.060791,0.032059,150.0
117,0.059871,-0.044642,-0.021295,0.087287,0.045213,0.031567,-0.047082,0.071210,0.079122,0.135612,281.0
121,0.063504,-0.044642,0.017506,0.021872,0.008063,0.021546,-0.036038,0.034309,0.019907,0.011349,173.0
154,0.067136,0.050680,0.020739,-0.005670,0.020446,0.026243,-0.002903,-0.002592,0.008641,0.003064,197.0
175,0.067136,-0.044642,-0.038540,-0.026328,-0.031840,-0.026366,0.008142,-0.039493,-0.027129,0.003064,127.0
192,0.056239,0.050680,-0.030996,0.008101,0.019070,0.021233,0.033914,-0.039493,-0.029526,-0.059067,91.0
200,0.056239,-0.044642,-0.057941,-0.007977,0.052093,0.049103,0.056003,-0.021412,-0.028323,0.044485,158.0
202,0.081666,0.050680,0.001339,0.035644,0.126395,0.091065,0.019187,0.034309,0.084492,-0.030072,196.0
204,0.110727,0.050680,0.006728,0.028758,-0.027712,-0.007264,-0.047082,0.034309,0.002004,0.077622,277.0
211,0.092564,-0.044642,0.036907,0.021872,-0.024960,-0.016658,0.000779,-0.039493,-0.022517,-0.021788,70.0
212,0.067136,-0.044642,0.003494,0.035644,0.049341,0.031254,0.070730,-0.039493,-0.000612,0.019633,73.0
217,0.074401,-0.044642,0.031517,0.101058,0.046589,0.036890,0.015505,-0.002592,0.033654,0.044485,296.0
227,0.067136,0.050680,-0.029918,0.057437,-0.000193,-0.015719,0.074412,-0.050564,-0.038460,0.007207,108.0
233,0.067136,-0.044642,0.036907,-0.050427,-0.023584,-0.034508,0.048640,-0.039493,-0.025953,-0.038357,90.0
235,0.067136,0.050680,-0.014828,0.058608,-0.059359,-0.034508,-0.061809,0.012906,-0.005142,0.048628,124.0
237,0.056239,-0.044642,-0.068719,-0.068778,-0.000193,-0.001001,0.044958,-0.037648,-0.048359,-0.001078,72.0
253,0.081666,-0.044642,0.033673,0.008101,0.052093,0.056619,-0.017629,0.034309,0.034866,0.069338,150.0
258,0.078034,0.050680,-0.024529,-0.042406,0.006687,0.052861,-0.069172,0.080804,-0.037129,0.056912,89.0
267,0.059871,-0.044642,-0.000817,-0.084856,0.075484,0.079478,0.004460,0.034309,0.023371,0.027917,115.0
273,0.074401,0.050680,-0.020218,0.045972,0.074108,0.032819,-0.036038,0.071210,0.106351,0.036201,241.0
278,0.067136,0.050680,-0.036385,-0.084856,-0.007073,0.019667,-0.054446,0.034309,0.001148,0.032059,102.0
282,0.070769,-0.044642,-0.005128,-0.005670,0.087868,0.102965,0.011824,0.034309,-0.008943,0.027917,230.0
288,0.070769,0.050680,-0.016984,0.021872,0.043837,0.056305,0.037595,-0.002592,-0.070209,-0.017646,80.0
291,0.074401,-0.044642,0.018584,0.063187,0.061725,0.042840,0.008142,-0.002592,0.058038,-0.059067,248.0
296,0.067136,-0.044642,-0.061174,-0.040099,-0.026336,-0.024487,0.033914,-0.039493,-0.056153,-0.059067,89.0
303,0.074401,-0.044642,0.034751,0.094172,0.057597,0.020293,0.022869,-0.002592,0.073799,-0.021788,236.0
307,0.067136,0.050680,-0.030996,0.004658,0.024574,0.035638,-0.028674,0.034309,0.023371,0.081764,172.0
318,0.088931,-0.044642,0.006728,0.025315,0.030078,0.008707,0.063367,-0.039493,0.009434,0.032059,109.0
323,0.070769,0.050680,-0.007284,0.049415,0.060349,-0.004445,-0.054446,0.108111,0.129021,0.056912,248.0
331,0.081666,0.050680,-0.025607,-0.036656,-0.070367,-0.046407,-0.039719,-0.002592,-0.041176,-0.005220,199.0
342,0.056239,0.050680,0.021817,0.056301,-0.007073,0.018101,-0.032356,-0.002592,-0.023647,0.023775,178.0
345,0.081666,0.050680,-0.002973,-0.033213,0.042462,0.057871,-0.010266,0.034309,-0.000612,-0.001078,139.0
371,0.052606,0.050680,-0.009439,0.049415,0.050717,-0.019163,-0.013948,0.034309,0.119340,-0.017646,197.0
388,0.052606,0.050680,-0.024529,0.056301,-0.007073,-0.005072,-0.021311,-0.002592,0.026717,-0.038357,110.0
397,0.052606,-0.044642,-0.004050,-0.030907,-0.046975,-0.058307,-0.013948,-0.025840,0.036060,0.023775,198.0
399,0.059871,0.050680,0.022895,0.049415,0.016318,0.011838,-0.013948,-0.002592,0.039542,0.019633,232.0
402,0.110727,0.050680,-0.033151,-0.022885,-0.004321,0.020293,-0.061809,0.071210,0.015568,0.044485,168.0
408,0.063504,-0.044642,-0.050396,0.107944,0.031454,0.019354,-0.017629,0.023608,0.058038,0.040343,189.0
414,0.081666,0.050680,0.006728,-0.004534,0.109883,0.117056,-0.032356,0.091875,0.054720,0.007207,131.0
431,0.070769,0.050680,-0.030996,0.021872,-0.037344,-0.047034,0.033914,-0.039493,-0.014960,-0.001078,66.0

**문제 3. 새로운 열 생성**
* **문제 설명:** 'bmi' 열과 'bp' 열을 사용하여 'bmi_bp_ratio'라는 새로운 열을 만드세요. (bmi / bp)
* **HINT:** `df['새로운 컬럼명'] = df['기존 컬럼1'] / df['기존 컬럼2']` 형태로 새로운 열을 생성해 보세요.

In [22]:
from sklearn.datasets import load_diabetes
import pandas as pd
diabetes = load_diabetes()
df = pd.DataFrame(diabetes.data, columns=diabetes.feature_names)
df['target'] = diabetes.target

df['bmi_bp_ratio'] = df['bmi']/df['bp']
new_df =df[['bmi','bp','bmi_bp_ratio']]
new_df 
# 코드를 작성하세요
# 예상 출력: 'bmi_bp_ratio' 열이 추가된 DataFrame

          bmi        bp  bmi_bp_ratio
0    0.061696  0.021872      2.820735
1   -0.051474 -0.026328      1.955142
2    0.044451 -0.005670     -7.839136
3   -0.011595 -0.036656      0.316319
4   -0.036385  0.021872     -1.663499
..        ...       ...           ...
437  0.019662  0.059744      0.329098
438 -0.015906 -0.067642      0.235155
439 -0.015906  0.017293     -0.919788
440  0.039062  0.001215     32.142522
441 -0.073030 -0.081413      0.897033

[442 rows x 3 columns]

**문제 4. 그룹별 평균 BMI 계산**
* **문제 설명:** 'sex' 열을 기준으로 데이터를 그룹화하고, 각 그룹의 'bmi'에 대한 평균(mean)과 표준편차(std)를 한 번에 계산하세요.
* **HINT:** `df.groupby()`를 사용하여 그룹화한 뒤, `['bmi'].agg(['mean', 'std'])` 메서드를 적용해 보세요.

In [26]:
from sklearn.datasets import load_diabetes
import pandas as pd
diabetes = load_diabetes()
df = pd.DataFrame(diabetes.data, columns=diabetes.feature_names)
df['target'] = diabetes.target

df['target']
# 코드를 작성하세요
# 예상 출력: 성별 bmi의 평균과 표준편차

df.groupby('sex')['bmi'].agg(['mean','std'])

               mean       std
sex
-0.044642 -0.003936  0.049269
 0.050680  0.004468  0.045379

**문제 5. 'target' 열의 값 빈도 계산**
* **문제 설명:** 'target' 열의 고유한 값들과 그 빈도를 계산하세요.
* **HINT:** `.value_counts()` 메서드를 사용하면 Series 내의 고유한 값들의 빈도를 계산할 수 있습니다.

In [ ]:
from sklearn.datasets import load_diabetes
import pandas as pd
diabetes = load_diabetes()
df = pd.DataFrame(diabetes.data, columns=diabetes.feature_names)
df['target'] = diabetes.target


df['target'].value_counts()
# 코드를 작성하세요
# 예상 출력: target 값의 빈도 수

target
200.0    6
72.0     6
90.0     5
178.0    5
71.0     5
        ..
73.0     1
222.0    1
86.0     1
79.0     1
57.0     1
Name: count, Length: 214, dtype: int64

---

#### **3. 캘리포니아 주택 가격 데이터셋 (California Housing Dataset)**

**문제 1. 데이터 불러오기 및 통계 요약**
* **문제 설명:** scikit-learn에서 캘리포니아 주택 데이터를 불러와 DataFrame으로 만드세요. `.describe()` 메서드를 사용하여 각 열의 통계량을 요약하세요.
* **HINT:** `fetch_california_housing()` 함수로 데이터를 불러온 후 `pd.DataFrame()`으로 만드세요. `housing.feature_names`를 `columns`로 지정해야 합니다.

In [28]:
from sklearn.datasets import fetch_california_housing
import pandas as pd

housing = fetch_california_housing()
df = pd.DataFrame(housing.data, columns = housing.feature_names)
df['target'] = housing.target
# 코드를 작성하세요
# 예상 출력: 각 열의 count, mean, std 등 요약 통계

**문제 2. 특정 조건으로 데이터 선택**
* **문제 설명:** 'median_income'이 8.0보다 큰 행만 필터링하여 DataFrame을 만드세요.
* **HINT:** `df['median_income'] > 8.0`이라는 불리언 조건으로 DataFrame을 필터링해 보세요.

In [40]:
from sklearn.datasets import fetch_california_housing
import pandas as pd
housing = fetch_california_housing()
df = pd.DataFrame(housing.data, columns=housing.feature_names)
df['target'] = housing.target


housing_df = df[df['MedInc'] > 8.0] 
housing_df

# 코드를 작성하세요
# 예상 출력: 'median_income'이 8.0보다 큰 행들로만 구성된 DataFrame

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,target
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.52600
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.58500
131,11.6017,18.0,8.335052,1.082474,533.0,2.747423,37.84,-122.19,3.92600
134,8.2049,28.0,6.978947,0.968421,463.0,2.436842,37.83,-122.19,3.35200
135,8.4010,26.0,7.530806,1.056872,542.0,2.568720,37.83,-122.20,3.51200
...,...,...,...,...,...,...,...,...,...
20426,10.0472,11.0,9.890756,1.159664,415.0,3.487395,34.18,-118.69,5.00001
20427,8.6499,4.0,7.236059,1.032528,5495.0,2.553439,34.19,-118.80,5.00001
20428,8.7288,6.0,8.715842,1.102970,3385.0,3.351485,34.23,-118.83,4.25800
20436,12.5420,10.0,9.873315,1.102426,1179.0,3.177898,34.21,-118.69,5.00001
20503,8.2787,27.0,6.935065,1.103896,243.0,3.155844,34.33,-118.75,3.30000

**문제 3. 새로운 열 생성**
* **문제 설명:** 'households' 열과 'population' 열을 사용하여 'population_per_household'라는 새로운 열을 만드세요. (population / households)
* **HINT:** `df['새로운 컬럼명'] = df['기존 컬럼1'] / df['기존 컬럼2']` 형태로 새로운 열을 생성해 보세요.

In [72]:
from sklearn.datasets import fetch_california_housing
import pandas as pd
housing = fetch_california_housing()
df = pd.DataFrame(housing.data, columns=housing.feature_names)
df['target'] = housing.target
df
# population_per_household = (population/households)

df['Population_per_HouseAge'] = df['Population']/df['HouseAge'] 
df['Population_per_HouseAge']
# 코드를 작성하세요
# 예상 출력: 'population_per_household' 열이 추가된 DataFrame

0          7.853659
1        114.333333
2          9.538462
3         10.730769
4         10.865385
            ...
20635     33.800000
20636     19.777778
20637     59.235294
20638     41.166667
20639     86.687500
Name: Population_per_HouseAge, Length: 20640, dtype: float64

**문제 4. 'ocean_proximity' 열의 값 빈도 계산**
* **문제 설명:** 'ocean_proximity' 열의 고유한 값들과 그 빈도를 계산하세요.
* **HINT:** `.value_counts()` 메서드를 사용하면 Series 내의 고유한 값들의 빈도를 계산할 수 있습니다.

In [67]:
import pandas as pd
data = {
    'ocean_proximity': ['NEAR BAY', '<1H OCEAN', 'NEAR BAY', 'INLAND', '<1H OCEAN'],
    'median_income': [3.87, 4.21, 5.01, 2.50, 6.15]
}
df = pd.DataFrame(data)
df
df['ocean_proximity'].value_counts()

# 코드를 작성하세요
# 예상 출력: ocean_proximity 값의 빈도 수

ocean_proximity
NEAR BAY     2
<1H OCEAN    2
INLAND       1
Name: count, dtype: int64

**문제 5. 데이터 정렬**
* **문제 설명:** 'median_house_value' 열을 기준으로 데이터를 오름차순으로 정렬하세요.
* **HINT:** `.sort_values()` 메서드를 사용하고 `by='컬럼명'`을 지정해 보세요. `ascending=True`가 기본값이므로 생략할 수 있습니다.

In [73]:
from sklearn.datasets import fetch_california_housing
import pandas as pd
housing = fetch_california_housing()
df = pd.DataFrame(housing.data, columns=housing.feature_names)
df['target'] = housing.target
df.rename(columns={'target': 'median_house_value'}, inplace=True)

df['median_house_value'].sort_values()

# 코드를 작성하세요
# 예상 출력: 'median_house_value' 값이 작은 순서대로 정렬된 DataFrame

9188     0.14999
19802    0.14999
2799     0.14999
2521     0.14999
5887     0.17500
          ...
16938    5.00001
16936    5.00001
16935    5.00001
8291     5.00001
18055    5.00001
Name: median_house_value, Length: 20640, dtype: float64